// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veojetlvpyhtsfmkocgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlb2pldGx2cHlodHNmbWtvY2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ2MDksImV4cCI6MjA2NTc1MDYwOX0.-9xB6oo2jNciRrDSfK_d0434PKnFnNlOpFUQx5ik0YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);